version: 3
endpoint: https://exciting-anteater-17.hasura.app
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: migrations
seeds_directory: seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: https://exciting-anteater-17.hasura.app

